[package]
name = "soft"
version = "0.1.0"
authors = ["notkild <notkild@gmail.com>"]

[dependencies]
app_dirs = "1.1"
error-chain = "0.7"

[[bin]]
name = "soft-daemon"
path = "daemon/main.rs"

[[bin]]
name = "soft-cli"
path = "cli/main.rs"
